stages:
  prepare:
    cmd: python save_dataset.py --config ./configs/resnet_baseconf.yaml
    deps:
      - save_dataset.py
      - src/data.py
    # outs:
    #   - datasets/ExtraSmall_test
    #   - datasets/ExtraSmall_train
  testing:
    cmd: python testing_code.py
    deps:
      - src
      - testing_code.py
  train:
    cmd: COMET_API_KEY='YOUR API' CUDA_VISIBLE_DEVICES=0 python train.py --config ./configs/resnet_baseconf.yaml
    deps:
      - train.py
    outs:
      - base_resnet_50_pretrained
  evaluate:
    cmd: python inference.py --config ./configs/resnet_baseconf.yaml > inference_output.txt
    deps:
      - inference.py
      - base_resnet_50_pretrained
    outs:
      - inference_output.txt